Repository shinhan-instock/backend, pull requests merged in 2025-03, with the labels that each got.

#31 pr stock_detail_api modified
  stock-module/src/main/java/com/pda/stock_module/domain/common/RedisCommon.java
  stock-module/src/main/java/com/pda/stock_module/repository/StockQueryRepository.java
  stock-module/src/main/java/com/pda/stock_module/service/StockQueryService.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockController.java
  stock-module/src/main/java/com/pda/stock_module/web/dto/DetailStockResponse.java
Labels: :recycle: Refactoring

#37 Feat(#35) 좋아요 top10 마일리지 부여 배치처리 완료
  build.gradle
  community-module/src/main/java/com/pda/community_module/batch/decider/MidnightDecider.java
  community-module/src/main/java/com/pda/community_module/batch/job/BatchJobConfiguration.java
  community-module/src/main/java/com/pda/community_module/batch/scheduler/BatchScheduler.java
  community-module/src/main/java/com/pda/community_module/batch/task/likeTop10/LikeTop10Processor.java
  community-module/src/main/java/com/pda/community_module/batch/task/likeTop10/LikeTop10Reader.java
  community-module/src/main/java/com/pda/community_module/batch/task/likeTop10/LikeTop10StepConfiguration.java
  community-module/src/main/java/com/pda/community_module/batch/task/likeTop10/LikeTop10Writer.java
  community-module/src/main/java/com/pda/community_module/batch/task/likeTop10/MileageFeignClient.java
  community-module/src/main/java/com/pda/community_module/batch/task/likeTop10/MileageRequest.java
  community-module/src/main/java/com/pda/community_module/batch/task/sentimentAnalysis/SentimentAnalysisProcessor.java
  community-module/src/main/java/com/pda/community_module/batch/task/sentimentAnalysis/SentimentAnalysisReader.java
  community-module/src/main/java/com/pda/community_module/batch/task/sentimentAnalysis/SentimentAnalysisStepConfiguration.java
  community-module/src/main/java/com/pda/community_module/batch/task/sentimentAnalysis/SentimentAnalysisWriter.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisProcessor.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisReader.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisStepConfiguration.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisWriter.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentReset/StockSentimentResetProcessor.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentReset/StockSentimentResetReader.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentReset/StockSentimentResetStepConfiguration.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentReset/StockSentimentResetWriter.java
  community-module/src/main/java/com/pda/community_module/batch/validator/TimeFormatJobParametersValidator.java
  community-module/src/main/java/com/pda/community_module/config/MileageFeignConfig.java
  community-module/src/main/java/com/pda/community_module/config/StockServiceClient.java
  community-module/src/main/java/com/pda/community_module/converter/UserConverter.java
  community-module/src/main/java/com/pda/community_module/repository/PostRepository.java
  community-module/src/main/java/com/pda/community_module/service/UserService.java
  community-module/src/main/java/com/pda/community_module/service/UserServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/UserController.java
  community-module/src/main/java/com/pda/community_module/web/dto/UserResponseDTO.java
  community-module/src/main/resources/application.yml
  piggyBank-module/src/main/java/com/pda/piggyBank_module/PiggyBankModuleApplication.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/config/UserFeignClient.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/converter/MileageConverter.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/domain/Piggy.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/domain/common/Piggy.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/repository/MileageRepository.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/repository/PiggyRepository.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/service/MileageService.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/service/MileageServiceImpl.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/web/controller/MileageController.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/web/dto/MileageRequest.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/web/dto/MileageResponseDto.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/web/dto/UserResponseDTO.java
Labels: :recycle: Refactoring, :sparkles: Feature

#42 refactor(#35) openfeign url 및 batch flow 수정
  community-module/src/main/java/com/pda/community_module/batch/job/BatchJobConfiguration.java
  community-module/src/main/java/com/pda/community_module/config/StockServiceClient.java
Labels: :recycle: Refactoring

#47 feat/#46-comment CRUD 생성
  community-module/src/main/java/com/pda/community_module/CommunityModuleApplication.java
  community-module/src/main/java/com/pda/community_module/converter/CommentConverter.java
  community-module/src/main/java/com/pda/community_module/domain/Comment.java
  community-module/src/main/java/com/pda/community_module/domain/PostCount.java
  community-module/src/main/java/com/pda/community_module/repository/CommentRepository.java
  community-module/src/main/java/com/pda/community_module/repository/PostCountRepository.java
  community-module/src/main/java/com/pda/community_module/service/CommentService.java
  community-module/src/main/java/com/pda/community_module/service/CommentServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/CommentController.java
  community-module/src/main/java/com/pda/community_module/web/dto/CommentResponseDTO.java
Labels: :sparkles: Feature

#49 [Refactor] 무한 스크롤 방식으로 댓글 조회 로직 변경
  community-module/src/main/java/com/pda/community_module/repository/CommentRepository.java
  community-module/src/main/java/com/pda/community_module/service/CommentService.java
  community-module/src/main/java/com/pda/community_module/service/CommentServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/CommentController.java
Labels: :recycle: Refactoring

#52 pr Feat/#32 검색어 자동완성
  stock-module/src/main/java/com/pda/stock_module/config/SchedulerConfig.java
  stock-module/src/main/java/com/pda/stock_module/domain/common/RedisCommon.java
  stock-module/src/main/java/com/pda/stock_module/service/FetchStockListService.java
  stock-module/src/main/java/com/pda/stock_module/service/StockSearchService.java
  stock-module/src/main/java/com/pda/stock_module/service/StockSearchServiceImpl.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockController.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockSearchController.java
Labels: :sparkles: Feature

#55 [커뮤니티 모듈] 댓글 기능 개선 및 S3 기반 이미지 처리 도입
  community-module/src/main/java/com/pda/community_module/converter/CommentConverter.java
  community-module/src/main/java/com/pda/community_module/domain/Comment.java
  community-module/src/main/java/com/pda/community_module/service/CommentService.java
  community-module/src/main/java/com/pda/community_module/service/CommentServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/CommentController.java
  community-module/src/main/java/com/pda/community_module/web/dto/CommentResponseDTO.java
Labels: :sparkles: Feature

#62 pr Feat/#59 내 계좌 보기
  community-module/src/main/java/com/pda/community_module/domain/OwnStock.java
  community-module/src/main/java/com/pda/community_module/domain/User.java
  community-module/src/main/java/com/pda/community_module/repository/AccountRepository.java
  community-module/src/main/java/com/pda/community_module/repository/OwnStockRepository.java
  community-module/src/main/java/com/pda/community_module/repository/UserRepository.java
  community-module/src/main/java/com/pda/community_module/service/AccountService.java
  community-module/src/main/java/com/pda/community_module/service/AccountServiceImpl.java
  community-module/src/main/java/com/pda/community_module/service/UserService.java
  community-module/src/main/java/com/pda/community_module/web/controller/AccountController.java
  community-module/src/main/java/com/pda/community_module/web/controller/UserController.java
  community-module/src/main/java/com/pda/community_module/web/dto/AccountRequestDTO.java
  community-module/src/main/java/com/pda/community_module/web/dto/AccountResponseDTO.java
  core-module/src/main/java/com/pda/core_module/apiPayload/code/status/ErrorStatus.java
  stock-module/src/main/java/com/pda/stock_module/domain/client/OwnStockClient.java
  stock-module/src/main/java/com/pda/stock_module/service/StockSearchService.java
  stock-module/src/main/java/com/pda/stock_module/service/StockSearchServiceImpl.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockSearchController.java
  stock-module/src/main/java/com/pda/stock_module/web/dto/AccountResponseDTO.java
Labels: :sparkles: Feature

#64 pr Feat/#63 마일리지 주식 선택
  community-module/src/main/java/com/pda/community_module/config/MileageClient.java
  community-module/src/main/java/com/pda/community_module/domain/OwnStock.java
  community-module/src/main/java/com/pda/community_module/repository/OwnStockRepository.java
  community-module/src/main/java/com/pda/community_module/service/AccountService.java
  community-module/src/main/java/com/pda/community_module/service/AccountServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/AccountController.java
  community-module/src/main/java/com/pda/community_module/web/dto/MileageRequestDTO.java
  community-module/src/main/java/com/pda/community_module/web/dto/MileageResponseDTO.java
  community-module/src/main/java/com/pda/community_module/web/dto/StockRequestDTO.java
  core-module/src/main/java/com/pda/core_module/apiPayload/code/status/ErrorStatus.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/PiggyBankModuleApplication.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/repository/PiggyRepository.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/service/MileageService.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/service/MileageServiceImpl.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/web/controller/MileageController.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/web/dto/MileageRequest.java
  stock-module/src/main/java/com/pda/stock_module/domain/client/MileageClient.java
  stock-module/src/main/java/com/pda/stock_module/service/StockSearchServiceImpl.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockController.java
  stock-module/src/main/java/com/pda/stock_module/web/dto/MileageResponseDTO.java
Labels: :sparkles: Feature

#58 Refactor(#57)-게시글-작성-kafka-적용
  build.gradle
  community-module/src/main/java/com/pda/community_module/config/KafkaConfig.java
  community-module/src/main/java/com/pda/community_module/config/OpenAiConfig.java
  community-module/src/main/java/com/pda/community_module/config/RestTemplateConfig.java
  community-module/src/main/java/com/pda/community_module/repository/SentimentRepository.java
  community-module/src/main/java/com/pda/community_module/saga/CommunitySaga.java
  community-module/src/main/java/com/pda/community_module/service/PostHistoryService.java
  community-module/src/main/java/com/pda/community_module/service/PostHistoryServiceImpl.java
  community-module/src/main/java/com/pda/community_module/service/PostService.java
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
  community-module/src/main/java/com/pda/community_module/service/SentimentService.java
  community-module/src/main/java/com/pda/community_module/service/SentimentServiceImpl.java
  community-module/src/main/java/com/pda/community_module/service/handler/CommunityCommandsHandler.java
  community-module/src/main/java/com/pda/community_module/web/dto/GPTRequestDTO.java
  community-module/src/main/java/com/pda/community_module/web/dto/GPTResponseDTO.java
  community-module/src/main/resources/application.yml
  core-module/src/main/java/com/pda/core_module/commands/FinalizePostCommand.java
  core-module/src/main/java/com/pda/core_module/commands/RollbackPostCommand.java
  core-module/src/main/java/com/pda/core_module/events/CheckStockEvent.java
  core-module/src/main/java/com/pda/core_module/events/FinishedPostEvent.java
  core-module/src/main/java/com/pda/core_module/events/RollbackEvent.java
  core-module/src/main/java/com/pda/core_module/events/SetMileageEvent.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/config/PiggyBankKafkaConfig.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/domain/Piggy.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/domain/common/BaseEntity.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/service/handler/PiggyBankCommandsHandler.java
  piggyBank-module/src/main/resources/application.yml
  stock-module/src/main/java/com/pda/stock_module/config/JpaConfig.java
  stock-module/src/main/java/com/pda/stock_module/config/KafkaProducerConfig.java
  stock-module/src/main/java/com/pda/stock_module/config/StockKafkaConfig.java
  stock-module/src/main/java/com/pda/stock_module/service/StockEventService.java
  stock-module/src/main/java/com/pda/stock_module/service/handler/StockCommandsHandler.java
  stock-module/src/main/resources/application.yml
Labels: :recycle: Refactoring, :sparkles: Feature

#69 Refactor(#68) gpt-api를-이용해-감정-분석-post_count-추가
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
  community-module/src/main/java/com/pda/community_module/service/SentimentService.java
  community-module/src/main/java/com/pda/community_module/service/SentimentServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/dto/GPTRequestDTO.java
Labels: :recycle: Refactoring

#80 Refactor(#79)-openfeign-주소-yml에서-주입
  community-module/src/main/java/com/pda/community_module/batch/task/likeTop10/MileageFeignClient.java
  community-module/src/main/java/com/pda/community_module/config/MileageClient.java
  community-module/src/main/java/com/pda/community_module/config/StockServiceClient.java
  community-module/src/main/java/com/pda/community_module/service/WatchListServiceImpl.java
  community-module/src/main/resources/application.yml
  piggyBank-module/src/main/java/com/pda/piggyBank_module/config/UserFeignClient.java
  piggyBank-module/src/main/java/com/pda/piggyBank_module/service/MileageServiceImpl.java
  piggyBank-module/src/main/resources/application.yml
  stock-module/src/main/java/com/pda/stock_module/domain/client/MileageClient.java
  stock-module/src/main/java/com/pda/stock_module/domain/client/OwnStockClient.java
  stock-module/src/main/resources/application.yml
Labels: :recycle: Refactoring

#81 pr Feat/#78 계좌 공개 여부 설정
  community-module/src/main/java/com/pda/community_module/batch/scheduler/BatchScheduler.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisReader.java
  community-module/src/main/java/com/pda/community_module/domain/User.java
  community-module/src/main/java/com/pda/community_module/service/AccountServiceImpl.java
  community-module/src/main/java/com/pda/community_module/service/UserService.java
  community-module/src/main/java/com/pda/community_module/service/UserServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/UserController.java
  core-module/src/main/java/com/pda/core_module/apiPayload/code/status/ErrorStatus.java
Labels: :sparkles: Feature

#84 Refactor/#83-req-post-02-게시글-수정-api-수정
  community-module/src/main/java/com/pda/community_module/converter/PostConverter.java
  community-module/src/main/java/com/pda/community_module/domain/common/BaseEntity.java
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
Labels: :recycle: Refactoring

#87 Refactor(#86) req stock 08 주식 상세 보기 수정
  community-module/src/main/java/com/pda/community_module/repository/WatchListRepository.java
  community-module/src/main/java/com/pda/community_module/service/WatchListService.java
  community-module/src/main/java/com/pda/community_module/service/WatchListServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/WatchListController.java
  stock-module/src/main/java/com/pda/stock_module/domain/client/CommunityClient.java
  stock-module/src/main/java/com/pda/stock_module/service/StockQueryService.java
  stock-module/src/main/java/com/pda/stock_module/service/StockSearchServiceImpl.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockController.java
  stock-module/src/main/java/com/pda/stock_module/web/dto/DetailStockResponse.java
Labels: :recycle: Refactoring

#90 Refactor(#89) req post 04 글 전체보기 수정
  community-module/src/main/java/com/pda/community_module/converter/PostConverter.java
  community-module/src/main/java/com/pda/community_module/repository/PostRepository.java
  community-module/src/main/java/com/pda/community_module/service/PostService.java
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/dto/PostResponseDTO.java
Labels: :recycle: Refactoring

#92 Refactor(#91)-req-post-04-글-개별보기-수정
  community-module/src/main/java/com/pda/community_module/converter/PostConverter.java
  community-module/src/main/java/com/pda/community_module/service/PostService.java
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/PostController.java
Labels: :recycle: Refactoring

#94 Refactor(#93) kafka bootstrap server url 변경
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockFeignClient.java
  community-module/src/main/resources/application.yml
  piggyBank-module/src/main/resources/application.yml
  stock-module/src/main/resources/application.yml
Labels: :recycle: Refactoring

#98 Refactor(#97)-req-stock-08-주식-상세-보기-수정
  stock-module/src/main/java/com/pda/stock_module/service/StockQueryService.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockController.java
Labels: :recycle: Refactoring

#105 pr sse connect
  community-module/src/main/java/com/pda/community_module/service/AccountService.java
  community-module/src/main/java/com/pda/community_module/service/AccountServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/AccountController.java
  community-module/src/main/java/com/pda/community_module/web/controller/UserController.java
  stock-module/src/main/java/com/pda/stock_module/service/RankingListService.java
  stock-module/src/main/java/com/pda/stock_module/service/StockQueryService.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockController.java
  stock-module/src/main/java/com/pda/stock_module/web/controller/StockRankingController.java
Labels: :sparkles: Feature

#109 Refactor(#108) req post 04 글 전체보기 페이징 기반으로 수정
  community-module/src/main/java/com/pda/community_module/repository/PostRepository.java
  community-module/src/main/java/com/pda/community_module/service/PostService.java
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/PostController.java
Labels: :recycle: Refactoring

#112 Revert "Refactor(#108) req post 04 글 전체보기 페이징 기반으로 수정"
  community-module/src/main/java/com/pda/community_module/repository/PostRepository.java
  community-module/src/main/java/com/pda/community_module/service/PostService.java
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/controller/PostController.java
Labels: :recycle: Refactoring

#114 pr Fix/#113 entiment 주식 상세정보에 추가, 타인 계좌 응답 수정
  community-module/src/main/java/com/pda/community_module/batch/scheduler/BatchScheduler.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisProcessor.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisReader.java
  community-module/src/main/java/com/pda/community_module/batch/task/stockSentimentAnalysis/StockSentimentAnalysisWriter.java
  community-module/src/main/java/com/pda/community_module/service/AccountServiceImpl.java
  stock-module/src/main/java/com/pda/stock_module/service/FetchStockListService.java
  stock-module/src/main/java/com/pda/stock_module/service/StockQueryService.java
  stock-module/src/main/java/com/pda/stock_module/web/dto/StockSentimentResponse.java
Labels: :recycle: Refactoring

#121 pr 주식 가격변화수정
  community-module/src/main/java/com/pda/community_module/service/AccountServiceImpl.java
Labels: :recycle: Refactoring

#123 pr Fix/#122 내주식 확인 응답수정
  community-module/src/main/java/com/pda/community_module/service/AccountServiceImpl.java
  community-module/src/main/java/com/pda/community_module/web/dto/AccountResponseDTO.java
Labels: :recycle: Refactoring

#127 pr connection
  community-module/src/main/resources/application-prod.yml
  community-module/src/main/resources/application.yml
  piggyBank-module/src/main/resources/application.yml
  stock-module/src/main/resources/application-prod.yml
Labels: :recycle: Refactoring

#131 Refactor(#130) req post 01 관련글 최신순 정렬 수정
  community-module/src/main/java/com/pda/community_module/repository/PostRepository.java
  community-module/src/main/java/com/pda/community_module/service/PostServiceImpl.java
Labels: :recycle: Refactoring

#133 Refact(#132)-req-post-01-관련글-최신순-정렬-수정
  community-module/src/main/java/com/pda/community_module/repository/PostRepository.java
Labels: :recycle: Refactoring
